Home task 3
PetrPoling/Homework pull request #8
Opened 2023-04-15 02:40 UTC by PetrPoling

Try hard

2023-04-24 04:55 UTC, vemontd1 requested changes

2023-04-24 04:55 UTC, vemontd1 commented on BLL/obj/BLL.csproj.nuget.dgspec.json
Fix .gitignore to exclude "**/obj/**" and "**/bin/**"

2023-04-24 04:55 UTC, vemontd1 commented on BLL/Services/BookingService.cs
> +            return await _unitOfWork.BookingRepository.GetBookingsByClass(classId);
Where _unitOfWork comes from?

2023-04-24 04:55 UTC, vemontd1 commented on BLL/Services/MemberService.cs
> +        }
Why not implemented?

2023-04-24 04:55 UTC, vemontd1 commented on UI/ConsoleManagers/SubscriptionConsoleManager.cs
> +        }
Methods shouldn't be larger than 40 lines. Better to refactor this, move some common logic to private methods

2023-04-24 04:55 UTC, vemontd1 commented on UI/ConsoleManagers/TrainerConsoleManager.cs
> +            return availableTrainers;
I think this can be simplified by using GetByPredicate

2023-04-26 16:16 UTC, PetrPoling commented on BLL/obj/BLL.csproj.nuget.dgspec.json
Thank you for check, already fixed

2023-04-26 16:46 UTC, PetrPoling commented on BLL/Services/MemberService.cs
> +        }
Tried to figure out how does member service works, Already implemented.

2023-04-26 16:50 UTC, PetrPoling commented on UI/ConsoleManagers/TrainerConsoleManager.cs
> +            return availableTrainers;
Checked and simplified.

2023-04-26 16:52 UTC, PetrPoling commented on BLL/obj/BLL.csproj.nuget.dgspec.json
Already done for all variants of obj and bin data

2023-04-26 16:53 UTC, PetrPoling commented on BLL/Services/BookingService.cs
> +            return await _unitOfWork.BookingRepository.GetBookingsByClass(classId);
Forget to change the name of service, Already debugged and fixed

2023-04-27 04:29 UTC, vemontd1 approved these changes

2023-04-27 10:36 UTC, merged